### ISSUE TITLE
read in demo VCF files with installed R package

### ISSUE THREAD

**Issue by yuchenjulia** [acc-bioinfo/TMBleR#2]
Hello, I've tried to run the docker image with demo data, it generates the result I want. Great job! However, when I installed the TMBleR R package locally or on server, there comes an error of demo when read the VCF files: 
vcfs <- readVcfFiles(vcfFiles = vcf_files, assembly = genome_assembly)
######################################################################
TMBleR/0.1.1 is loaded
Error in if (nchar(f[i, 2]) == 0) { : argument is of length zero
:Calls: readVcfFiles -> lapply -> FUN
#######################################################################
Could you help to check? Thank you!

**Comment by alessando-guida** [comment]
duplicated, see #1
